name: rl-robotics-macos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch==2.11.0
      - onnxscript==0.7.0
      - mujoco==3.7.0
      - gymnasium[mujoco]==1.2.3
      - tensorboard==2.20.0
      - tensorboardX==2.6.5
      - mediapy==1.2.6
      - matplotlib==3.10.8
      - onnx==1.21.0
      - onnxruntime==1.25.1
      - jupyterlab==4.5.6
      - ipykernel
